### ISSUE TITLE
Need more config and detail.

### ISSUE THREAD

**Issue by PanDaMeow** [huaaaliu/RGBX_Semantic_Segmentation#4]
Hello! This is a great work! I wonder if you can provide more config files for different X modal experiments.

I train the MFNet RGB-T with mit_b2 backbone, modifing the config as follow (The other part are the same as the repo):

```
# Dataset config
"""Dataset Path"""
C.dataset_name = 'MFNetRGBT'
C.dataset_path = osp.join(C.root_dir, 'datasets', 'MFNetRGBT')
C.rgb_root_folder = osp.join(C.dataset_path, 'RGB')
C.rgb_format = '.png'
C.gt_root_folder = osp.join(C.dataset_path, 'Label')
C.gt_format = '.png'
C.gt_transform = False
# True when label 0 is invalid, you can also modify the function _transform_gt in dataloader.RGBXDataset
# True for most dataset valid, Faslse for MFNet(?)
C.x_root_folder = osp.join(C.dataset_path, 'Thermal')
C.x_format = '.png'
C.x_is_single_channel = True # True for raw depth, thermal and aolp/dolp(not aolp/dolp tri) input
C.train_source = osp.join(C.dataset_path, "train.txt")
C.eval_source = osp.join(C.dataset_path, "test.txt")
C.is_test = False
C.num_train_imgs = 1176
C.num_eval_imgs = 393
C.num_classes = 9
C.class_names =  ["Unlabeled", "Car", "Person", "Bike", "Curve", "Car Stop", "Guardrail", "Color Cone", "Bump"]
```
I merge the train.txt and val.txt in MFNet dataset as train.txt and test.txt in MFNet dataset as test.txt. After that, there are 1176 train imgs and 393 eval imgs. Then I used 8x 2080Ti training.

Finally, I get the `mean_IoU 58.200%` , Although consistent with the paper, I found Guardrail IOU just 0.211%, far from 8.1% in paper. Then I use the weight you provide, the result is `mean_IoU 58.985%`, and all class IOU looks good.

So, my question is:
1. Is my config or seeting correct, why I use the weight you provide but get the better result than paper.
2. Why I trained 500 epoch, get the Guardrail IOU just 0.211%

And I'm appreciate it if you can provide more config files for different X modal experiments, so that I can understand it better.

Many thanks to your wonderful work!

**Comment by huaaaliu** [comment]
Hi, thank you for your interest on our work. 
I think you config is correct, however, I notice that you trained the model with 8 GPUs, so you may use a larger batch size (we set the batch size to 8, and trained on 4 2080Ti). For more implementation details of other datasets, you can refer to the appendix of our paper.
Besides, the mIoU is different in different trainings even they use the same training settings. The reason is that some categories only appears in few images on the training and testset (guardrail). The result iou of these categories will not be very robust (unbalanced dataset), and causes a difference on mIoU.

**Comment by PanDaMeow** [comment]
Thanks for your reply!
